import { Difficulty, LevelConfig, MathTopic } from '../types';

export interface ExtendedLevelConfig extends LevelConfig {
  tier: 1 | 2 | 3 | 4 | 5;
  tierName: string;
  icon: string;
}

// Generate 50 progressive levels spanning all key concepts
export const GAME_LEVELS: ExtendedLevelConfig[] = [
  // TIER 1: LEVELS 1 - 10 (ROOKIE EXPLORER - EASY)
  {
    id: 1,
    name: 'Level 1: Number Sparks',
    difficulty: 'easy',
    description: 'Foundational single & double digit addition basics',
    requiredAccuracy: 70,
    topics: ['addition'],
    tier: 1,
    tierName: 'Rookie Explorer',
    icon: '🌱',
  },
  {
    id: 2,
    name: 'Level 2: Quick Subtraction',
    difficulty: 'easy',
    description: 'Fast take-away drills and mental math',
    requiredAccuracy: 70,
    topics: ['subtraction'],
    tier: 1,
    tierName: 'Rookie Explorer',
    icon: '➖',
  },
  {
    id: 3,
    name: 'Level 3: Add & Subtract Blitz',
    difficulty: 'easy',
    description: 'Mixed addition and subtraction fluency',
    requiredAccuracy: 70,
    topics: ['addition', 'subtraction'],
    tier: 1,
    tierName: 'Rookie Explorer',
    icon: '⚡',
  },
  {
    id: 4,
    name: 'Level 4: Times Tables Starter',
    difficulty: 'easy',
    description: 'Multiplication basics and rapid times tables',
    requiredAccuracy: 70,
    topics: ['multiplication', 'tables'],
    tier: 1,
    tierName: 'Rookie Explorer',
    icon: '✖️',
  },
  {
    id: 5,
    name: 'Level 5: Fair Sharing Division',
    difficulty: 'easy',
    description: 'Simple division, equal groups and remainders',
    requiredAccuracy: 70,
    topics: ['division'],
    tier: 1,
    tierName: 'Rookie Explorer',
    icon: '➗',
  },
  {
    id: 6,
    name: 'Level 6: Four Operations Kickoff',
    difficulty: 'easy',
    description: 'Add, subtract, multiply & divide mixed drills',
    requiredAccuracy: 75,
    topics: ['addition', 'subtraction', 'multiplication', 'division'],
    tier: 1,
    tierName: 'Rookie Explorer',
    icon: '🎯',
  },
  {
    id: 7,
    name: 'Level 7: Fraction Slices',
    difficulty: 'easy',
    description: 'Halves, quarters, like-denominator additions',
    requiredAccuracy: 75,
    topics: ['fractions'],
    tier: 1,
    tierName: 'Rookie Explorer',
    icon: '🍕',
  },
  {
    id: 8,
    name: 'Level 8: Decimal Dots',
    difficulty: 'easy',
    description: 'Decimal place value and simple decimal additions',
    requiredAccuracy: 75,
    topics: ['decimals'],
    tier: 1,
    tierName: 'Rookie Explorer',
    icon: '🔢',
  },
  {
    id: 9,
    name: 'Level 9: Everyday Word Problems',
    difficulty: 'easy',
    description: 'Real-world math stories with friendly numbers',
    requiredAccuracy: 75,
    topics: ['word_problems'],
    tier: 1,
    tierName: 'Rookie Explorer',
    icon: '📖',
  },
  {
    id: 10,
    name: 'Level 10: Tier 1 Milestone Boss',
    difficulty: 'easy',
    description: 'Complete review of Tier 1 Explorer skills',
    requiredAccuracy: 75,
    topics: ['addition', 'subtraction', 'multiplication', 'division', 'fractions'],
    tier: 1,
    tierName: 'Rookie Explorer',
    icon: '🏆',
  },

  // TIER 2: LEVELS 11 - 20 (CADET CHALLENGER - MEDIUM)
  {
    id: 11,
    name: 'Level 11: Double Digit Power',
    difficulty: 'medium',
    description: 'Regrouping, carrying and borrowing with larger numbers',
    requiredAccuracy: 75,
    topics: ['addition', 'subtraction'],
    tier: 2,
    tierName: 'Cadet Challenger',
    icon: '🔋',
  },
  {
    id: 12,
    name: 'Level 12: Times Tables Pro',
    difficulty: 'medium',
    description: 'Master times tables 6 through 15 with speed',
    requiredAccuracy: 75,
    topics: ['tables', 'multiplication'],
    tier: 2,
    tierName: 'Cadet Challenger',
    icon: '🚀',
  },
  {
    id: 13,
    name: 'Level 13: Division Mastery',
    difficulty: 'medium',
    description: 'Two-digit quotients and finding factors',
    requiredAccuracy: 75,
    topics: ['division'],
    tier: 2,
    tierName: 'Cadet Challenger',
    icon: '✂️',
  },
  {
    id: 14,
    name: 'Level 14: Fraction Arithmetic',
    difficulty: 'medium',
    description: 'Unlike denominators and fraction subtraction',
    requiredAccuracy: 80,
    topics: ['fractions'],
    tier: 2,
    tierName: 'Cadet Challenger',
    icon: '🍰',
  },
  {
    id: 15,
    name: 'Level 15: Decimal Multiplication',
    difficulty: 'medium',
    description: 'Multiplying and subtracting decimal values accurately',
    requiredAccuracy: 80,
    topics: ['decimals'],
    tier: 2,
    tierName: 'Cadet Challenger',
    icon: '🪙',
  },
  {
    id: 16,
    name: 'Level 16: Percentage Basics',
    difficulty: 'medium',
    description: 'Calculate 10%, 25%, 50% and simple discounts',
    requiredAccuracy: 80,
    topics: ['percentage'],
    tier: 2,
    tierName: 'Cadet Challenger',
    icon: '％',
  },
  {
    id: 17,
    name: 'Level 17: Perimeter & Area',
    difficulty: 'medium',
    description: 'Squares, rectangles, triangles and perimeters',
    requiredAccuracy: 80,
    topics: ['geometry'],
    tier: 2,
    tierName: 'Cadet Challenger',
    icon: '📐',
  },
  {
    id: 18,
    name: 'Level 18: Negative Integers',
    difficulty: 'medium',
    description: 'Thermometer math: adding and subtracting negative numbers',
    requiredAccuracy: 80,
    topics: ['integers'],
    tier: 2,
    tierName: 'Cadet Challenger',
    icon: '🌡️',
  },
  {
    id: 19,
    name: 'Level 19: Word Problem Quest',
    difficulty: 'medium',
    description: 'Two-step shopping, distance and time word challenges',
    requiredAccuracy: 80,
    topics: ['word_problems'],
    tier: 2,
    tierName: 'Cadet Challenger',
    icon: '🧭',
  },
  {
    id: 20,
    name: 'Level 20: Cadet Boss Battle',
    difficulty: 'medium',
    description: 'Test all intermediate concepts to unlock Tier 3',
    requiredAccuracy: 80,
    topics: ['multiplication', 'division', 'fractions', 'percentage', 'geometry'],
    tier: 2,
    tierName: 'Cadet Challenger',
    icon: '🎖️',
  },

  // TIER 3: LEVELS 21 - 30 (WARRIOR CHAMPION - MEDIUM/HARD)
  {
    id: 21,
    name: 'Level 21: HCF & LCM Rush',
    difficulty: 'medium',
    description: 'Highest Common Factor and Lowest Common Multiple',
    requiredAccuracy: 80,
    topics: ['division', 'multiplication'],
    tier: 3,
    tierName: 'Warrior Champion',
    icon: '🔗',
  },
  {
    id: 22,
    name: 'Level 22: Ratios & Sharing',
    difficulty: 'medium',
    description: 'Divide quantities in given ratios and comparisons',
    requiredAccuracy: 80,
    topics: ['fractions', 'division'],
    tier: 3,
    tierName: 'Warrior Champion',
    icon: '⚖️',
  },
  {
    id: 23,
    name: 'Level 23: Secret Algebra X',
    difficulty: 'hard',
    description: 'Solve one-step and two-step equations for x',
    requiredAccuracy: 80,
    topics: ['algebra'],
    tier: 3,
    tierName: 'Warrior Champion',
    icon: '🔍',
  },
  {
    id: 24,
    name: 'Level 24: Fraction Multipliers',
    difficulty: 'hard',
    description: 'Multiplying and dividing fractions with simplification',
    requiredAccuracy: 80,
    topics: ['fractions'],
    tier: 3,
    tierName: 'Warrior Champion',
    icon: '🧁',
  },
  {
    id: 25,
    name: 'Level 25: Profit & Loss Pro',
    difficulty: 'hard',
    description: 'Cost price, selling price, profit percentage and discounts',
    requiredAccuracy: 80,
    topics: ['percentage', 'word_problems'],
    tier: 3,
    tierName: 'Warrior Champion',
    icon: '💰',
  },
  {
    id: 26,
    name: 'Level 26: Angle Detectives',
    difficulty: 'hard',
    description: 'Complementary, supplementary, and triangle angle sums',
    requiredAccuracy: 80,
    topics: ['geometry'],
    tier: 3,
    tierName: 'Warrior Champion',
    icon: '📏',
  },
  {
    id: 27,
    name: 'Level 27: Integer Operations Lab',
    difficulty: 'hard',
    description: 'Multiplication and division of positive and negative numbers',
    requiredAccuracy: 80,
    topics: ['integers'],
    tier: 3,
    tierName: 'Warrior Champion',
    icon: '❄️',
  },
  {
    id: 28,
    name: 'Level 28: Averages & Data',
    difficulty: 'hard',
    description: 'Calculate mean, median and simple statistical averages',
    requiredAccuracy: 80,
    topics: ['division', 'addition'],
    tier: 3,
    tierName: 'Warrior Champion',
    icon: '📊',
  },
  {
    id: 29,
    name: 'Level 29: Speedy Mental Math',
    difficulty: 'hard',
    description: 'Rapid-fire mixed calculations without pen and paper',
    requiredAccuracy: 80,
    topics: ['multiplication', 'tables', 'addition', 'subtraction'],
    tier: 3,
    tierName: 'Warrior Champion',
    icon: '⚡',
  },
  {
    id: 30,
    name: 'Level 30: Champion Arena Boss',
    difficulty: 'hard',
    description: 'Conquer the arena with 10 high-intensity problems',
    requiredAccuracy: 80,
    topics: ['algebra', 'geometry', 'percentage', 'integers', 'fractions'],
    tier: 3,
    tierName: 'Warrior Champion',
    icon: '⚔️',
  },

  // TIER 4: LEVELS 31 - 40 (MATH WIZARD - HARD)
  {
    id: 31,
    name: 'Level 31: Linear Equations',
    difficulty: 'hard',
    description: 'Solve ax + b = c with positive and negative solutions',
    requiredAccuracy: 80,
    topics: ['algebra'],
    tier: 4,
    tierName: 'Math Wizard',
    icon: '🔮',
  },
  {
    id: 32,
    name: 'Level 32: Exponents & Powers',
    difficulty: 'hard',
    description: 'Squares, cubes, powers of 10 and indices laws',
    requiredAccuracy: 80,
    topics: ['multiplication', 'algebra'],
    tier: 4,
    tierName: 'Math Wizard',
    icon: '💥',
  },
  {
    id: 33,
    name: 'Level 33: Circle Secrets',
    difficulty: 'hard',
    description: 'Circumference (2πr) and area (πr²) formulas',
    requiredAccuracy: 80,
    topics: ['geometry'],
    tier: 4,
    tierName: 'Math Wizard',
    icon: '⭕',
  },
  {
    id: 34,
    name: 'Level 34: Percentage Wizardry',
    difficulty: 'hard',
    description: 'Percentage increase, decrease and multi-step changes',
    requiredAccuracy: 85,
    topics: ['percentage'],
    tier: 4,
    tierName: 'Math Wizard',
    icon: '📈',
  },
  {
    id: 35,
    name: 'Level 35: Surface Area & Volume',
    difficulty: 'hard',
    description: 'Cube, cuboid and cylinder volume calculation',
    requiredAccuracy: 85,
    topics: ['geometry'],
    tier: 4,
    tierName: 'Math Wizard',
    icon: '🧊',
  },
  {
    id: 36,
    name: 'Level 36: Algebraic Substitution',
    difficulty: 'hard',
    description: 'Evaluate 2x² + 3x - 5 when x is given',
    requiredAccuracy: 85,
    topics: ['algebra'],
    tier: 4,
    tierName: 'Math Wizard',
    icon: '🧪',
  },
  {
    id: 37,
    name: 'Level 37: Coordinate Plane',
    difficulty: 'hard',
    description: 'Points (x, y), quadrants and distances on the grid',
    requiredAccuracy: 85,
    topics: ['geometry'],
    tier: 4,
    tierName: 'Math Wizard',
    icon: '🗺️',
  },
  {
    id: 38,
    name: 'Level 38: Probability Basics',
    difficulty: 'hard',
    description: 'Coins, dice, colored marbles and chance calculations',
    requiredAccuracy: 85,
    topics: ['fractions', 'word_problems'],
    tier: 4,
    tierName: 'Math Wizard',
    icon: '🎲',
  },
  {
    id: 39,
    name: 'Level 39: Pythagorean Theorem',
    difficulty: 'hard',
    description: 'Right triangles and finding the hypotenuse (a² + b² = c²)',
    requiredAccuracy: 85,
    topics: ['geometry', 'algebra'],
    tier: 4,
    tierName: 'Math Wizard',
    icon: '🔺',
  },
  {
    id: 40,
    name: 'Level 40: Wizard Citadel Boss',
    difficulty: 'hard',
    description: 'High-level synthesis test of algebra and geometry',
    requiredAccuracy: 85,
    topics: ['algebra', 'geometry', 'percentage', 'word_problems'],
    tier: 4,
    tierName: 'Math Wizard',
    icon: '🧙',
  },

  // TIER 5: LEVELS 41 - 50 (GRANDMASTER LEGEND - EXPERT)
  {
    id: 41,
    name: 'Level 41: Simultaneous Equations',
    difficulty: 'expert',
    description: 'Two linear equations with two unknown variables',
    requiredAccuracy: 85,
    topics: ['algebra'],
    tier: 5,
    tierName: 'Grandmaster Legend',
    icon: '⚡',
  },
  {
    id: 42,
    name: 'Level 42: Trigonometry Basics',
    difficulty: 'expert',
    description: 'Sine, Cosine, Tangent values in right-angled triangles',
    requiredAccuracy: 85,
    topics: ['geometry'],
    tier: 5,
    tierName: 'Grandmaster Legend',
    icon: '📐',
  },
  {
    id: 43,
    name: 'Level 43: Arithmetic Progression (AP)',
    difficulty: 'expert',
    description: 'First term a, common difference d, and finding the nth term',
    requiredAccuracy: 85,
    topics: ['algebra'],
    tier: 5,
    tierName: 'Grandmaster Legend',
    icon: '🪜',
  },
  {
    id: 44,
    name: 'Level 44: Quadratic Equation Basics',
    difficulty: 'expert',
    description: 'Roots, factorization and finding values of x',
    requiredAccuracy: 85,
    topics: ['algebra'],
    tier: 5,
    tierName: 'Grandmaster Legend',
    icon: '🧬',
  },
  {
    id: 45,
    name: 'Level 45: Mensuration & Cylinder Volumes',
    difficulty: 'expert',
    description: 'Advanced 3D shapes, cone and sphere volume formulas',
    requiredAccuracy: 85,
    topics: ['geometry'],
    tier: 5,
    tierName: 'Grandmaster Legend',
    icon: '🪐',
  },
  {
    id: 46,
    name: 'Level 46: Advanced Probability & Odds',
    difficulty: 'expert',
    description: 'Independent events, cards and compound chances',
    requiredAccuracy: 85,
    topics: ['fractions', 'word_problems'],
    tier: 5,
    tierName: 'Grandmaster Legend',
    icon: '🎯',
  },
  {
    id: 47,
    name: 'Level 47: Coordinate Distances & Slopes',
    difficulty: 'expert',
    description: 'Midpoint, slope and distance formula between two points',
    requiredAccuracy: 85,
    topics: ['geometry'],
    tier: 5,
    tierName: 'Grandmaster Legend',
    icon: '📈',
  },
  {
    id: 48,
    name: 'Level 48: Olympiad Speed Run',
    difficulty: 'expert',
    description: 'Rapid-thinking competitive mathematics challenges',
    requiredAccuracy: 85,
    topics: ['algebra', 'geometry', 'multiplication', 'percentage'],
    tier: 5,
    tierName: 'Grandmaster Legend',
    icon: '👑',
  },
  {
    id: 49,
    name: 'Level 49: The Legend Gauntlet',
    difficulty: 'expert',
    description: '10 intense questions across all curriculum domains',
    requiredAccuracy: 85,
    topics: ['algebra', 'geometry', 'fractions', 'decimals', 'percentage', 'integers'],
    tier: 5,
    tierName: 'Grandmaster Legend',
    icon: '🔥',
  },
  {
    id: 50,
    name: 'Level 50: Ultimate Grandmaster Champion',
    difficulty: 'expert',
    description: 'The pinnacle of Topper Math Hero! Prove supreme mastery.',
    requiredAccuracy: 90,
    topics: ['algebra', 'geometry', 'word_problems', 'percentage', 'fractions'],
    tier: 5,
    tierName: 'Grandmaster Legend',
    icon: '🌟',
  },
];
